name: "Invalidations"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  evaluate-invalidations:
    name: "Evaluate Invalidations"
    uses: "SciML/.github/.github/workflows/invalidations.yml@v1"
